export interface ServerClockAnchor {
  serverTime: number;
  receivedAt: number;
}

export function advanceServerClockAnchor(
  current: ServerClockAnchor | undefined,
  serverTime: number,
  receivedAt: number,
): ServerClockAnchor {
  if (current && serverTime < current.serverTime) return current;
  return { serverTime, receivedAt };
}

/** Estimates relay time without comparing timestamps generated by two phones. */
export function estimateServerNow(
  anchor: ServerClockAnchor | undefined,
  localNow: number,
  measuredOffsetMs?: number,
): number {
  if (measuredOffsetMs !== undefined) return localNow + measuredOffsetMs;
  if (!anchor) return localNow;
  return anchor.serverTime + Math.max(0, localNow - anchor.receivedAt);
}

export function isServerTimestampFresh(
  lastSeenAtServer: number,
  serverNow: number,
  maximumAgeMs: number,
): boolean {
  return lastSeenAtServer >= serverNow - maximumAgeMs && lastSeenAtServer <= serverNow + 2_000;
}
