import type { StoryRoom } from '../types';
import { at, before, evidenceStage, rotatingParts, slots } from './catalog-evidence';

/** Retired content retained for source/history reference, not a selectable room. */
export const DEAD_AIR_ROOM: Omit<StoryRoom, 'id'> & { id: 'dead-air' } = {
  id: 'dead-air', title: 'Dead Air', subtitle: 'Fix the museum’s secret speaking tubes.',
  opening: 'The family’s welcome film is ready, but the museum’s speaking tubes are crossed. Turn the pipes, rescue a trapped decoration, and reconnect the right rooms before the guests arrive.',
  ending: 'The projection booth gets its cue, the garden hears the music, and the repair conversation stays private. The welcome film rolls. You repaired a whole building with a toolbox and each other’s observations.',
  accent: '#EF985B', paper: '#FFF1DE', minutes: 22, attemptLimit: 5,
  roles: ['Listener', 'Tube keeper', 'Stagehand', 'Projectionist'],
  stages: [
    evidenceStage({
      id: 'dead-air-echoes', title: 'Join the speaking tube', kind: 'circuit', layout: 'grid',
      story: 'Four loose pipe bends sit between the mouthpiece and receiver. Make one unbroken tube through all four.',
      objective: 'Connect mouthpiece to receiver.',
      instruction: 'Set your pieces, then use Quarter turn to join their open ends. Use all four pipes. Your partner controls the hidden pieces.',
      ...rotatingParts('tube', ['Upper-left pipe', 'Upper-right pipe', 'Lower-left pipe', 'Lower-right pipe']),
      interaction: { kind: 'pipe-grid', tiles: [[0, 1], [0, 1], [0, 1], [0, 1]], source: { cell: 0, edge: 3 }, target: { cell: 1, edge: 1 } },
      answer: ['tube-0-2', 'tube-1-1', 'tube-2-0', 'tube-3-3'],
      revelation: 'The receiver wakes up. Its inspection window shows the real blockage: a party streamer caught behind a grille.',
      explanation: 'The mouthpiece enters from the left. The upper-left bend goes down, the lower-left bend goes right, the lower-right bend goes up, and the upper-right bend exits right. Every open end meets another pipe or a receiver.',
      hints: ['Start at the mouthpiece. Its first bend cannot go through the outside edge.', 'Trace a single line with your finger. An open end must meet the open end of the next pipe.'],
    }, [
      { id: 'pipe-receiver', title: 'Receiver window', medium: 'note', lines: ['The receiver is outside the upper-right pipe.', 'Tell its owner: the tube must leave through the right edge.'], rules: [] },
      { id: 'pipe-floor', title: 'Bottom service hatch', medium: 'note', lines: ['The two lower pipes must join each other.', 'Their other ends must point back up into the cabinet.'], rules: [] },
      { id: 'pipe-last-bend', title: 'The booth’s sketch', medium: 'note', lines: ['The lower-right pipe carries the message up to the receiver pipe.', 'Ask its owner to join the left and top openings.'], rules: [] },
      { id: 'pipe-mouthpiece', title: 'Mouthpiece socket', medium: 'note', lines: ['The message enters the upper-left pipe from outside the left edge.', 'It needs to turn down; the top edge is sealed.'], rules: [] },
    ]),
    evidenceStage({
      id: 'dead-air-inside', title: 'The tiny repair kit', kind: 'investigation',
      story: 'A streamer is hiding behind the grille. Prepare the four repair points using the kit. Your partner has the labels you cannot see.',
      objective: 'Choose a tool for each repair point.',
      instruction: 'Tap a repair point, then choose its tool. Compare the private inspection notes. Each tool can be used once; one is spare.',
      slots: slots('Grille latch', 'Dark bend', 'Trapped streamer', 'Leaking collar'),
      interaction: { kind: 'workbench', sites: [
        { label: 'Grille latch', icon: 'lock-closed', description: 'A small recessed fastener.' },
        { label: 'Dark bend', icon: 'git-branch', description: 'Something is hidden around the corner.' },
        { label: 'Trapped streamer', icon: 'flag', description: 'Paper caught behind a narrow gap.' },
        { label: 'Leaking collar', icon: 'ellipse', description: 'A join that will not hold pressure.' },
      ] },
      options: [
        { id: 'coin', label: 'Brass coin', detail: 'A broad, flat edge', icon: 'ellipse' },
        { id: 'mirror', label: 'Pocket mirror', detail: 'A view around corners', icon: 'browsers' },
        { id: 'tweezers', label: 'Long tweezers', detail: 'A narrow, gentle grip', icon: 'git-branch' },
        { id: 'wax', label: 'Soft sealing wax', detail: 'Fills a small gap', icon: 'water' },
        { id: 'hammer', label: 'Wooden mallet', detail: 'For knocking loose panels', icon: 'hammer' },
      ],
      answer: ['coin', 'mirror', 'tweezers', 'wax'],
      revelation: 'The kit is ready. The mirror shows that the streamer is caught, not glued. Stop the airflow before lifting it out.',
      explanation: 'The latch has a wide slot that fits the coin. The mirror lets you see around the bend. Tweezers grip the paper through the narrow gap. Soft wax seals the collar without striking the delicate tube; the mallet stays in the kit.',
      hints: ['Describe the problem in your inspection note to the person who controls that repair point.', 'Think about the job: turn, see, grip, or seal. Match a tool to each job.'],
    }, [
      { id: 'repair-kit-dark', title: 'Around the bend', medium: 'note', lines: ['The Dark bend is lit, but the corner hides the snag.', 'You need to look around it—not make the light brighter.'], rules: [at('mirror', 1)] },
      { id: 'repair-kit-paper', title: 'A delicate grip', medium: 'note', lines: ['The Trapped streamer is paper. The gap is too thin for fingers.', 'Use the narrow tool that grips without tearing.'], rules: [at('tweezers', 2)] },
      { id: 'repair-kit-collar', title: 'A hairline leak', medium: 'note', lines: ['The Leaking collar is not loose. It has a tiny gap.', 'Fill the gap with something soft; do not hit it.'], rules: [at('wax', 3)] },
      { id: 'repair-kit-latch', title: 'The latch close up', medium: 'lens', illustration: 'duct', scanTargetSeat: 0, diagram: { nodes: ['Wide straight slot', 'Flat coin edge'], caption: 'The latch turns with a flat disc. There is no keyhole.' }, lines: ['The Grille latch has one broad, straight slot.', 'A flat round object from the kit fits it.'], rules: [at('coin', 0)] },
    ]),
    evidenceStage({
      id: 'dead-air-repair', title: 'Rescue the streamer', kind: 'sequence',
      story: 'The tube is delicate. Agree on the repair order, then let the little museum machine carry it out.',
      objective: 'Make a safe four-step repair.',
      instruction: 'Arrange the four actions from first to last. Read each safety note aloud. This is an on-screen repair—leave real vents alone.',
      slots: slots('Begin here', 'Then', 'After that', 'Finish with'),
      options: [
        { id: 'pull', label: 'Lift out the paper', detail: 'Use the prepared tweezers', icon: 'flag' },
        { id: 'stop', label: 'Stop the airflow', detail: 'Release the pull on the paper', icon: 'pause-circle' },
        { id: 'boost', label: 'Boost the fan', detail: 'Pull the paper harder', icon: 'flash' },
        { id: 'test', label: 'Test the clear tube', detail: 'Check the finished repair', icon: 'checkmark-circle' },
        { id: 'open', label: 'Open the grille', detail: 'Reach the trapped paper', icon: 'grid' },
      ],
      answer: ['stop', 'open', 'pull', 'test'],
      revelation: 'The streamer slides out intact. On its back are the opening-night destinations. You can now reconnect the building.',
      explanation: 'Stop the airflow so the streamer is no longer pulled tight. Open the grille to reach it. Lift the paper out with the tweezers. Only then test the repaired tube. Boosting the fan would tighten the snag instead of freeing it.',
      hints: ['What is pulling the paper tight? Deal with that before opening anything.', 'You cannot remove what you cannot reach. The check belongs after the repair.'],
    }, [
      { id: 'repair-stop', title: 'Pressure label', medium: 'note', lines: ['Stop the airflow before opening the grille.', 'A stronger fan makes the snag tighter.'], rules: [before('stop', 'open')] },
      { id: 'repair-access', title: 'Access label', medium: 'note', lines: ['The grille must be open before the paper can be lifted out.'], rules: [before('open', 'pull')] },
      { id: 'repair-test', title: 'Receiver checklist', medium: 'note', lines: ['Test the tube after the paper is out—not while it is still caught.'], rules: [before('pull', 'test')] },
      { id: 'repair-care', title: 'Stagehand’s reminder', medium: 'note', lines: ['The only useful actions are stop, open, lift, and test.', 'Boosting the fan is not a repair.'], rules: [{ kind: 'exclude', item: 'boost' }] },
    ]),
    evidenceStage({
      id: 'dead-air-private', title: 'Who hears what?', kind: 'routing',
      story: 'The pipes work. The plugs do not: the hall must not hear the private repair call. Match each message to the right room.',
      objective: 'Patch four messages to four rooms.',
      instruction: 'Connect a message to each room socket. These are separate connections, not a route. Ask your partner who needs to hear what.',
      slots: slots('Projection booth', 'Public hall', 'Roof garden', 'Repair desk'),
      interaction: { kind: 'patch-panel' },
      options: [
        { id: 'film', label: 'Start the film', detail: 'A cue for the projector', icon: 'film' },
        { id: 'welcome', label: 'Welcome, everyone', detail: 'The public announcement', icon: 'people' },
        { id: 'music', label: 'Garden music', detail: 'A quiet outdoor playlist', icon: 'musical-notes' },
        { id: 'private', label: 'Repair complete', detail: 'The crew’s private report', icon: 'construct' },
        { id: 'alarm', label: 'Fire-drill test', detail: 'A cancelled rehearsal', icon: 'notifications' },
      ],
      answer: ['film', 'welcome', 'music', 'private'],
      revelation: 'All four connections are right. The film starts; the hall hears its welcome; music reaches the garden. Your repair report stays with the crew.',
      explanation: 'The projection booth needs the start cue. The public hall receives the welcome. Garden guests asked for music. The repair desk gets the private repair report. The cancelled drill is not connected to any room.',
      hints: ['Read your receiver’s request to the person controlling that socket.', 'The messages travel separately. You are matching an audience to a message, not arranging a sequence.'],
    }, [
      { id: 'patch-hall', title: 'Front-door request', medium: 'note', lines: ['The Public hall is full of arriving guests.', 'They need the welcome, not the crew’s repair conversation.'], rules: [at('welcome', 1)] },
      { id: 'patch-garden', title: 'A note from the roof', medium: 'note', lines: ['The Roof garden is ready for a quiet playlist.', 'Keep spoken announcements indoors.'], rules: [at('music', 2)] },
      { id: 'patch-desk', title: 'Crew-only request', medium: 'note', lines: ['The Repair desk is the only private receiver.', 'Send the repair report there.'], rules: [at('private', 3)] },
      { id: 'patch-booth', title: 'The projectionist’s card', medium: 'note', lines: ['The Projection booth is waiting to start the film.', 'The fire-drill rehearsal was cancelled.'], rules: [at('film', 0)] },
    ]),
  ],
};
