import type { StoryRoom } from '../types';
import { BENCH_WIRING_STAGE } from './bench-wiring-stage';
import { CLOCKWORK_STAGE } from './clockwork-stage';

export const LINE13_ROOM: StoryRoom = {
  id: 'line-13', title: 'AFTER HOURS', subtitle: 'One last delivery in a toy-maker’s workshop',
  opening: 'The toy-maker has left one unfinished surprise: a miniature town with a missing clock. Connect its residents, plot the delivery, route power through its streets, operate the crane and build a little machine to bring the clock to life.',
  ending: 'Your handmade mechanism turns the town clock. The tiny streets glow, the parade begins, and the toy-maker’s surprise is ready for the family waiting outside.',
  accent: '#F5B476', paper: '#F5DFB5', minutes: 22, attemptLimit: 5,
  roles: ['The Maker', 'The Map Keeper', 'The Mechanic', 'The Spotter'],
  stages: [
    {
      id: 'callers', title: 'Wake the little town', kind: 'investigation',
      story: 'Four residents of the miniature town left messages on the toy-maker’s switchboard. The address labels have fallen off. Your family holds the missing descriptions.',
      objective: 'Connect each resident to the right building.',
      instruction: 'Choose your coloured cable, then tap a building. Ask your partner what its resident can see.',
      interaction: { kind: 'patch-panel' },
      slots: ['Blue caller', 'Red caller', 'Green caller', 'Yellow caller'].map((label, seat) => ({ id: `caller-${seat}`, label, seat })),
      options: [
        { id: 'kitchen', label: 'Bakery', detail: 'Fresh bread in the tiny high street', icon: 'restaurant-outline' },
        { id: 'porch', label: 'Front porch', detail: 'A little roof beside the front door', icon: 'home-outline' },
        { id: 'workshop', label: 'Workshop', detail: 'Where broken things get another chance', icon: 'construct-outline' },
        { id: 'garden', label: 'Garden', detail: 'A tiny orchard beside the town', icon: 'leaf-outline' },
        { id: 'lift', label: 'Clock tower', detail: 'The unfinished centrepiece', icon: 'time-outline' },
        { id: 'cellar', label: 'Store room', detail: 'Crates of miniature furniture', icon: 'archive-outline' },
      ],
      clues: [
        { id: 'caller-red', title: 'Red caller’s note', seat: 0, medium: 'note',
          lines: ['“I am outside, but the little roof keeps me dry. There is a WELCOME mat beside my feet.”', 'Tell the person holding the red cable where this caller is.'] },
        { id: 'caller-green', title: 'Green caller’s note', seat: 3, medium: 'note',
          lines: ['“A half-built birdhouse is clamped to the bench. There are tools and wood shavings everywhere.”', 'Tell the person holding the green cable where this caller is.'] },
        { id: 'caller-yellow', title: 'Yellow caller’s note', seat: 2, medium: 'note',
          lines: ['“The hose is tangled around a lemon tree. Mud is getting on my shoes.”', 'Tell the person holding the yellow cable where this caller is.'] },
        { id: 'caller-blue', title: 'Blue caller’s note', seat: 1, medium: 'note',
          lines: ['“A loaf is cooling beside the oven. The cooking timer will not stop ringing.”', 'Tell the person holding the blue cable where this caller is.'] },
      ],
      constraints: [{ kind: 'at', item: 'kitchen', slot: 0 }, { kind: 'at', item: 'porch', slot: 1 }, { kind: 'at', item: 'workshop', slot: 2 }, { kind: 'at', item: 'garden', slot: 3 }],
      answer: ['kitchen', 'porch', 'workshop', 'garden'],
      revelation: 'Four windows light up. The residents have left a delivery order for the unfinished clock tower. Its parcel is waiting beside the little train.',
      explanation: 'Blue describes bread and an oven: the bakery. Red is sheltered beside a welcome mat: the porch. Green sees a workbench and tools: the workshop. Yellow sees a tree and hose: the garden. The clock tower and store room have no matching message.',
      hints: ['Start with one caller. Ask a teammate to read the note with that cable’s color.', 'Match a place to the objects in the note. These are everyday locations, not a secret code.'],
    },
    {
      id: 'rescue-route', title: 'A parcel through town', kind: 'routing',
      story: 'The tiny delivery cart needs a route. One of you knows where the parcel starts; the others know what to collect and where it belongs.',
      objective: 'Plan a four-stop delivery through the model town.',
      instruction: 'Choose your numbered stop, then tap a building. The cart must follow the drawn tracks.',
      interaction: {
        kind: 'route-map',
        nodes: [
          { id: 'platform', label: 'Train stop', x: 25, y: 15, icon: 'train-outline' },
          { id: 'relay', label: 'Post office', x: 75, y: 15, icon: 'mail-outline' },
          { id: 'ticket', label: 'Sweet shop', x: 25, y: 50, icon: 'ice-cream-outline' },
          { id: 'workshop', label: 'Workshop', x: 75, y: 50, icon: 'construct-outline' },
          { id: 'boiler', label: 'Bakery', x: 25, y: 85, icon: 'restaurant-outline' },
          { id: 'gate', label: 'Clock square', x: 75, y: 85, icon: 'time-outline' },
        ],
        edges: [['platform', 'relay'], ['platform', 'ticket'], ['relay', 'workshop'], ['ticket', 'workshop'], ['ticket', 'boiler'], ['workshop', 'gate'], ['boiler', 'gate']],
      },
      slots: [
        { id: 'route-start', label: 'Start', seat: 0 },
        { id: 'route-relay', label: 'Collect its label', seat: 1 },
        { id: 'route-tool', label: 'Collect the crank', seat: 2 },
        { id: 'route-exit', label: 'Deliver', seat: 3 },
      ],
      options: [
        { id: 'platform', label: 'Train stop', detail: 'A parcel waits beside the train', icon: 'train-outline' },
        { id: 'relay', label: 'Post office', detail: 'Labels, stamps and delivery slips', icon: 'mail-outline' },
        { id: 'ticket', label: 'Sweet shop', detail: 'A window full of treats', icon: 'ice-cream-outline' },
        { id: 'workshop', label: 'Workshop', detail: 'Spare tools and hand cranks', icon: 'construct-outline' },
        { id: 'boiler', label: 'Bakery', detail: 'Bread and a busy oven', icon: 'restaurant-outline' },
        { id: 'gate', label: 'Clock square', detail: 'The unfinished town clock', icon: 'time-outline' },
      ],
      clues: [
        { id: 'route-phone', title: 'First, its address', seat: 0, medium: 'note',
          lines: ['The parcel has no label. Its first stop after collection must be where letters and stamps are sold.', 'Tell the person placing stop 2.'] },
        { id: 'route-start', title: 'Waiting for collection', seat: 1, medium: 'note',
          lines: ['The parcel arrived by train. It is still on the platform beside the engine.', 'Tell the person placing stop 1.'] },
        { id: 'route-exit', title: 'The missing centrepiece', seat: 2, medium: 'note',
          lines: ['The delivery completes the clock in the town square. No shop ordered this parcel.', 'Tell the person placing stop 4.'] },
        { id: 'route-tool', title: 'A little lifting help', seat: 3, medium: 'note',
          lines: ['The delivery crane needs a hand crank. A spare hangs beside the repair bench.', 'Collect it after the address label, before the final delivery. Tell the person placing stop 3.'] },
      ],
      constraints: [
        { kind: 'at', item: 'platform', slot: 0 },
        { kind: 'at', item: 'relay', slot: 1 },
        { kind: 'at', item: 'workshop', slot: 2 },
        { kind: 'at', item: 'gate', slot: 3 },
      ],
      answer: ['platform', 'relay', 'workshop', 'gate'],
      revelation: 'The parcel reaches clock square with its label and crank. The toy-maker’s crane needs power before it can lift the last piece into place.',
      explanation: 'Start at the train stop. Collect the address label at the post office, the crank at the workshop, and deliver to clock square. These four stops follow connected tracks. The bakery and sweet shop are distractions, not needed stops.',
      hints: ['Which note tells you where the parcel starts?', 'Each stop has a job. Ask who knows where its useful object is kept.', 'Follow connected tracks, visiting the label before the crank.'],
    },
    BENCH_WIRING_STAGE,
    {
      id: 'last-delivery', title: 'The last delivery', kind: 'investigation',
      story: 'A wooden crane hangs above the model town. One screen sees the bays from above; another sees the hook from the side. The lever opens the crossing or unfolds the receiving tray—but never both.',
      objective: 'Lift the parcel and deliver it to the gold tray.',
      instruction: 'Use your own controls and tell the others what you can see. The parcel cannot pass through the divider or drop from mid-air.',
      interaction: { kind: 'rescue-crane' },
      slots: ['Travel rail', 'Hoist', 'Bridge', 'Grabber'].map((label, seat) => ({ id: `crane-${seat}`, label, seat })),
      options: [], clues: [], constraints: [], answer: [],
      revelation: 'The parcel lands safely on the gold tray. Inside is the missing clock—but its drive is unfinished. Four little belt units wait on the toy-maker’s pegboard.',
      explanation: 'Move the trolley over the parcel at bay 2, lower to the floor and close the grabber. Lift to Clearance or High. Open the crossing, travel to bay 6, then unfold the gold tray. Lower to the floor and release. The rail operator sees the bays; the hoist operator sees the divider. Neither can complete the lift alone.',
      hints: ['First line up the hook with the parcel. Who can see its bay, and who can lower the hook?', 'Carry the parcel above the divider. The bridge lever opens a crossing but folds the tray away.', 'Once you cross, the receiving tray needs to be unfolded again before you can deliver.'],
    },
    CLOCKWORK_STAGE,
  ],
};
