import type { StoryRoom } from '../types';
import { at, evidenceStage, rotatingParts, slots } from './catalog-evidence';

export const NIGHT_GLASS_ROOM: StoryRoom = {
  id: 'night-glass', title: 'Barjeel', subtitle: 'One courtyard. Two different times.',
  opening: 'In an old Emirati courtyard house, coloured glass hides a curious viewer. Restore it together, explore the house across two times, and reopen a forgotten rooftop garden. The house is inspired by courtyard architecture; its time-crossing mystery is imaginary.',
  ending: 'The postcard fills with light: a garden invitation, waiting all these years. Past and present finally share an open doorway. Your family steps beneath the wind tower and out into the rooftop garden.',
  accent: '#E4C28A', paper: '#EEE2C6', minutes: 20, attemptLimit: 5,
  roles: ['Light keeper', 'Explorer', 'Garden keeper', 'Door keeper'],
  stages: [
    {
      id: 'night-glass-negative', title: 'A house made of light', kind: 'investigation',
      story: 'Four pieces of coloured glass sit in the courtyard window. Together they make a little house.',
      objective: 'Turn your glass. Make the house together.',
      instruction: 'Turn your coloured pieces until the shared picture matches the house. No hidden clues—just look, talk, and try.',
      ...rotatingParts('film', ['Amber slide', 'Mint slide', 'Rose slide', 'Blue slide']),
      interaction: {
        kind: 'lightbox', films: [[10, 11, 12, 16], [16, 17, 18, 22], [10, 11, 16, 21], [1, 2]],
        colors: ['#EAA546', '#70C8AC', '#DF849C', '#76AADE'],
        target: [2, 6, 7, 8, 10, 11, 12, 13, 14, 16, 18, 21, 22, 23],
      },
      answer: ['film-0-1', 'film-1-3', 'film-2-0', 'film-3-2'],
      clues: [], constraints: [],
      revelation: 'The glass becomes a house. Its little doorway points to a dusty viewer tucked beneath the courtyard window.',
      explanation: 'The four pieces make the house when Amber is turned once clockwise, Mint once anticlockwise, Rose stays in its starting position, and Blue is turned twice. Every piece starts on the table already; no setting or locking is needed.',
      hints: ['Turn one piece at a time and watch how the shared picture changes.', 'Describe a gap in the house. Ask who can turn their piece into that space.'],
    },
    {
      id: 'night-glass-passage', title: 'Something out of reach', kind: 'investigation',
      story: 'The viewer is locked. Its iron key has slipped beneath a grate. Each person can explore a different corner of the courtyard.',
      objective: 'Find a way to open and clear the viewer.',
      instruction: 'Search your corner. Share your finds, make a useful tool, and use it on the room.',
      slots: slots('Cupboard', 'Writing desk', 'Grate and tool bench', 'Locked viewer'),
      interaction: { kind: 'tool-search' }, options: [], answer: [], clues: [], constraints: [],
      revelation: 'A magnet and cord lift the lost key. The cover opens, the dust clears—and the viewer shows two versions of the very same courtyard.',
      explanation: 'Search the top cupboard drawer for a cloth and the bottom drawer for a cord. Lift the desk mat to find a magnet. At the grate, select the cord and magnet from the shared bag and combine them. Lower the tool to lift the iron key. The viewer keeper uses the key, then the cloth to clear its dusty glass.',
      hints: ['Search different corners before trying to solve everything alone. Finds enter a shared bag automatically.', 'The key is iron, but out of reach. What could attract it—and what could make that tool longer?'],
    },
    {
      id: 'night-glass-courtyard', title: 'Then becomes now', kind: 'investigation',
      story: 'Some phones see the courtyard years ago. Others see it today. The same house responds across time: a shutter changes daylight, and a young plant grows into roots.',
      objective: 'Open the rooftop passage together.',
      instruction: 'Change the old courtyard. Tell each other what changes in the house today, then explore what becomes reachable.',
      slots: slots('Old shutter', 'Wall today', 'Young plant', 'Door today'),
      interaction: { kind: 'time-house' }, options: [], answer: [], clues: [], constraints: [],
      revelation: 'A small change years ago makes room for everyone today. The doorway opens onto the rooftop. Beside it lies a blank postcard and the viewer’s missing optical parts.',
      explanation: 'Open the old shutter wide so light reaches the present-day wall. Move the young plant to the courtyard edge: it will neither shade the wall nor grow across the door. The wall explorer can now find a brass pin. The door keeper uses that pin to release the catch, then opens the cleared doorway. You can also collect the pin before moving the plant away from the door.',
      hints: ['A change on one phone can have its result on another. Describe what moved, brightened, or became blocked.', 'The door has two obstacles: a small catch and grown roots. The wall may hide something useful when it has daylight.'],
    },
    evidenceStage({
      id: 'night-glass-watermark', title: 'Read with daylight', kind: 'circuit',
      story: 'On the rooftop, a postcard waits beside four optical fittings. It is not empty: its picture appears when daylight passes through it.',
      objective: 'Fit the postcard’s daylight reader.',
      instruction: 'Tap your fitting, then choose the part it needs. Your family’s notes explain the jobs. Build the viewer together.',
      slots: slots('Harsh light', 'Blurry picture', 'Empty picture frame', 'Distracting side light'),
      interaction: { kind: 'patch-panel' },
      options: [
        { id: 'hood', label: 'Black viewing hood', detail: 'Keeps light from entering at the sides', icon: 'eye' },
        { id: 'mirror', label: 'Mirror sheet', detail: 'Sends light back', icon: 'browsers' },
        { id: 'lens', label: 'Convex lens', detail: 'Brings an image into focus', icon: 'ellipse' },
        { id: 'diffuser', label: 'Frosted diffuser', detail: 'Softens a harsh beam', icon: 'sunny' },
        { id: 'card', label: 'Blank postcard', detail: 'Thin paper holding a watermark', icon: 'mail' },
      ],
      answer: ['diffuser', 'lens', 'card', 'hood'],
      revelation: 'A garden invitation glows inside the postcard. The picture matches the open rooftop doorway. A place was waiting for your whole family, on both sides of time.',
      explanation: 'Frosted glass softens the harsh light. The convex lens focuses the blurry picture. The postcard fits the empty picture frame so light can reveal its watermark. The black hood blocks distracting side light. The mirror would send the light away from the reader.',
      hints: ['Each note describes a job rather than a position. Match that job to what a part actually does.', 'The picture is inside the paper. It must sit where the viewer holds its image.'],
    }, [
      { id: 'reader-focus', title: 'A blurry view', medium: 'note', lines: ['The Blurry picture needs a part that bends light into focus.', 'The maker used a curved clear lens, not a mirror.'], rules: [at('lens', 1)] },
      { id: 'reader-paper', title: 'The empty frame', medium: 'note', lines: ['The Empty picture frame is postcard-sized.', 'Light must pass through the paper to show its watermark.'], rules: [at('card', 2)] },
      { id: 'reader-sides', title: 'Light from the wrong place', medium: 'note', lines: ['Distracting side light must be blocked, not made brighter.', 'The dark part wraps around the viewer’s eye opening.'], rules: [at('hood', 3)] },
      { id: 'reader-sun', title: 'The maker’s riddle', medium: 'note', lines: ['“I am glass that clouds the sun, so you can see what light has done.”', 'Use that part where the light is too harsh.'], rules: [at('diffuser', 0)] },
    ]),
  ],
};
